// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

type AccessTokenProvider = (() => Promise<string | null>) | null;

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

export const SUPABASE_CONFIG_ERROR_MESSAGE =
  'Missing Supabase environment variables. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or NEXT_PUBLIC_* equivalents).';

export const SUPABASE_CONFIG = {
  url: SUPABASE_URL ?? null,
  publishableKey: SUPABASE_PUBLISHABLE_KEY ?? null,
  isConfigured: Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY),
} as const;

let accessTokenProvider: AccessTokenProvider = null;

const authAwareFetch: typeof fetch = async (input, init) => {
  if (!accessTokenProvider) {
    return fetch(input, init);
  }

  const token = await accessTokenProvider().catch(() => null);
  if (!token) {
    return fetch(input, init);
  }

  const headers = new Headers(init?.headers);
  headers.set('Authorization', `Bearer ${token}`);

  return fetch(input, {
    ...init,
    headers,
  });
};

const getBrowserStorage = () => {
  if (typeof window === 'undefined') {
    return undefined;
  }

  return window.localStorage;
};

const createUnconfiguredSupabaseClient = (): SupabaseClient<Database> => {
  const throwConfigError = () => {
    throw new Error(SUPABASE_CONFIG_ERROR_MESSAGE);
  };

  return new Proxy(
    {},
    {
      get() {
        throwConfigError();
      },
      set() {
        throwConfigError();
        return false;
      },
    },
  ) as SupabaseClient<Database>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = SUPABASE_CONFIG.isConfigured
  ? createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string, {
      auth: {
        storage: getBrowserStorage(),
        persistSession: true,
        autoRefreshToken: true,
      },
      global: {
        fetch: authAwareFetch,
      },
    })
  : createUnconfiguredSupabaseClient();

export function setSupabaseAccessTokenProvider(provider: AccessTokenProvider) {
  accessTokenProvider = provider;
}

export function clearSupabaseAccessTokenProvider() {
  accessTokenProvider = null;
}
